---
- hosts: jenkins
  become: yes

  tasks:
  - name: Install EPEL repository
    yum:
      name: epel-release
      state: present

  - name: Install Java
    yum:
      name: java-1.8.0-openjdk.x86_64
      state: present

  - name: Add Jenkins repository to Yum
    get_url:
      url: "https://pkg.jenkins.io/redhat-stable/jenkins.repo"
      dest: "/etc/yum.repos.d/jenkins.repo"

  - name: Import Jenkins repository key
    rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

  - name: Install Jenkins
    yum:
      name: jenkins
      state: present
      update_cache: yes

  - name: Enable Jenkins to start on boot and start the service
    service:
      name: jenkins
      state: started
      enabled: yes

  - name: Remove any previous versions of Docker
    yum:
      name: "{{ item.name }}"
      state: absent
    with_items:
      - { name: docker }
      - { name: docker-common }
      - { name: container-selinux }
      - { name: docker-engine-selinux }
      - { name: docker-engine }
      - { name: docker-ce }

  - name: Install packages for Docker
    yum:
      name: "{{ item.name }}"
      state: latest
    with_items:
      - { name: yum-utils }
      - { name: device-mapper-persistent-data }
      - { name: lvm2 }

  - name: Import Docker CE repository gpg key
    rpm_key:
      key: https://download.docker.com/linux/centos/gpg
      state: present

  - name: Add Docker CE repository
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
      force: yes
      owner: root
      group: root
      mode: 0644

  - name: Install Docker CE
    yum:
      name: docker-ce
      state: present
      update_cache: yes
