---
- hosts: jenkins
  become: yes

  tasks:
  - name: Install EPEL repository
    yum:
      name: epel-release
      state: present

  - name: Install Java
    yum:
      name: java-1.8.0-openjdk.x86_64
      state: present

  - name: Add Jenkins repository to Yum
    get_url:
      url: "https://pkg.jenkins.io/redhat-stable/jenkins.repo"
      dest: "/etc/yum.repos.d/jenkins.repo"

  - name: Import Jenkins repository key
    rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

  - name: Install Jenkins
    yum:
      name: jenkins
      state: present
      update_cache: yes

  - name: Enable Jenkins to start on boot and start the service
    service:
      name: jenkins
      state: started
      enabled: yes
